import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "SacyIA",
  description: "Generated by create next app",
  icons: {
    icon: "https://i.imgur.com/J2SO4bJ.png", // ✅ Ícone do site
    shortcut: "https://i.imgur.com/J2SO4bJ.png",
    apple: "https://i.imgur.com/J2SO4bJ.png",
  },
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={inter.variable}>
      <head>
        {/* Fallback para navegadores que não usam o metadata */}
        <link rel="icon" href="https://i.imgur.com/J2SO4bJ.png" type="image/png" />
      </head>
      <body className="min-h-screen bg-page text-gray-900 dark:text-gray-100">
        {children}
      </body>
    </html>
  );
}
